/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#4059aa",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#213145",
        "tertiary-fixed": "#e9ddff",
        "on-primary-container": "#90a8ff",
        "error-container": "#ffdad6",
        primary: "#00236f",
        "secondary-fixed": "#d8e2ff",
        "chart-green": "#22C55E",
        "sidebar-bg": "#0F172A",
        "surface-bright": "#f8f9ff",
        secondary: "#0058be",
        tertiary: "#340081",
        "on-surface": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-highest": "#d3e4fe",
        "tertiary-fixed-dim": "#d0bcff",
        "outline-variant": "#c5c5d3",
        "on-primary": "#ffffff",
        "chart-purple": "#A855F7",
        "on-primary-fixed-variant": "#264191",
        "background-subtle": "#F8FAFC",
        "on-tertiary-fixed-variant": "#5516be",
        outline: "#757682",
        "on-primary-fixed": "#00164e",
        danger: "#EF4444",
        "primary-fixed-dim": "#b6c4ff",
        "chart-yellow": "#FBBF24",
        "inverse-primary": "#b6c4ff",
        "on-tertiary-container": "#b89cff",
        "tertiary-container": "#4e03b8",
        "surface-variant": "#d3e4fe",
        "on-secondary-container": "#fefcff",
        "secondary-container": "#2170e4",
        "on-secondary-fixed": "#001a42",
        "surface-dim": "#cbdbf5",
        "chart-orange": "#F97316",
        "border-light": "#E2E8F0",
        success: "#10B981",
        "on-surface-variant": "#444651",
        "secondary-fixed-dim": "#adc6ff",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "inverse-on-surface": "#eaf1ff",
        "primary-container": "#1e3a8a",
        "chart-blue": "#1E3A8A",
        warning: "#F59E0B",
        "on-tertiary-fixed": "#23005c",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#004395",
        "on-background": "#0b1c30",
        background: "#f8f9ff",
        "primary-fixed": "#dce1ff",
        surface: "#f8f9ff",
        "surface-muted": "#F9FAFB",
        "border-subtle": "#E5E7EB",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "sidebar-width": "260px",
        "topbar-height": "64px",
        "widget-padding": "20px",
        gutter: "16px",
        "container-margin": "24px",
        "cell-padding-y": "16px",
        "cell-padding-x": "12px",
        "section-gap": "32px",
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-sm": ["Inter"],
        "data-display": ["Inter"],
        "data-subtext": ["Inter"],
        "data-mono": ["Inter"],
        "title-lg": ["Inter"],
        "display-lg": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "data-display": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "data-subtext": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
