\set ON_ERROR_STOP on

BEGIN;

-- 1. Migrate untouched legacy annual KPI values into the monthly source of truth.
-- Existing non-zero monthly plans are never overwritten. COUNT values are split as
-- whole numbers; MONEY values are split in cents. Remainders go to earlier months.
WITH legacy_targets AS (
    SELECT plan.id AS plan_id, definition.kpi_key, definition.value_type,
           CASE definition.kpi_key
               WHEN 'mql' THEN plan.mql_plan::numeric
               WHEN 'sql' THEN plan.sql_plan::numeric
               WHEN 'opportunity' THEN plan.opp_plan::numeric
               WHEN 'closed_deal' THEN plan.closed_deal_plan::numeric
               WHEN 'pipeline_value' THEN plan.pipeline_value_plan
               WHEN 'won_value' THEN plan.won_value_plan
           END AS annual_target
    FROM marketing.kpi_plans AS plan
    JOIN marketing.kpi_definitions AS definition
      ON definition.is_active
     AND definition.kpi_key IN
         ('mql', 'sql', 'opportunity', 'closed_deal', 'pipeline_value', 'won_value')
), untouched AS (
    SELECT target.*,
           CASE WHEN target.value_type = 'COUNT' THEN 1 ELSE 100 END AS scale
    FROM legacy_targets AS target
    JOIN marketing.kpi_monthly_plan_values AS monthly
      ON monthly.plan_id = target.plan_id
     AND monthly.kpi_key = target.kpi_key
    GROUP BY target.plan_id, target.kpi_key, target.value_type, target.annual_target
    HAVING count(*) = 12
       AND count(DISTINCT monthly.month) = 12
       AND sum(monthly.target_value) = 0
       AND target.annual_target <> 0
), allocated AS (
    SELECT untouched.plan_id, untouched.kpi_key, month_number,
           (
               floor(untouched.annual_target * untouched.scale / 12)
               + CASE
                   WHEN month_number <= mod(
                       (untouched.annual_target * untouched.scale)::bigint, 12
                   ) THEN 1 ELSE 0
                 END
           ) / untouched.scale AS monthly_target
    FROM untouched
    CROSS JOIN generate_series(1, 12) AS month_number
)
UPDATE marketing.kpi_monthly_plan_values AS monthly
SET target_value = allocated.monthly_target,
    updated_at = CURRENT_TIMESTAMP
FROM allocated
WHERE monthly.plan_id = allocated.plan_id
  AND monthly.kpi_key = allocated.kpi_key
  AND monthly.month = allocated.month_number;

-- Consumers must read this view instead of the duplicated legacy annual columns.
CREATE OR REPLACE VIEW marketing.kpi_plan_annual_totals AS
SELECT plan.id AS plan_id,
       plan.year,
       monthly.kpi_key,
       definition.label,
       definition.value_type,
       sum(monthly.target_value) AS annual_target
FROM marketing.kpi_plans AS plan
JOIN marketing.kpi_monthly_plan_values AS monthly ON monthly.plan_id = plan.id
JOIN marketing.kpi_definitions AS definition ON definition.kpi_key = monthly.kpi_key
WHERE definition.is_active
GROUP BY plan.id, plan.year, monthly.kpi_key,
         definition.label, definition.value_type;

COMMENT ON VIEW marketing.kpi_plan_annual_totals IS
    'Canonical annual KPI totals derived from monthly values; use instead of legacy annual columns';

-- 2. Preserve every OPP state. app.user_id may be set per transaction by callers.
CREATE TABLE IF NOT EXISTS marketing.opportunity_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id bigint NOT NULL,
    row_version bigint NOT NULL,
    operation character varying(10) NOT NULL,
    old_data jsonb,
    new_data jsonb,
    changed_by bigint,
    database_user_name text NOT NULL DEFAULT CURRENT_USER,
    transaction_id bigint NOT NULL DEFAULT txid_current(),
    changed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT opportunity_history_operation_check
        CHECK (operation IN ('BASELINE', 'INSERT', 'UPDATE', 'DELETE')),
    CONSTRAINT opportunity_history_changed_by_fkey
        FOREIGN KEY (changed_by) REFERENCES core.members(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS opportunity_history_version_operation_unique
    ON marketing.opportunity_history (opportunity_id, row_version, operation);

CREATE INDEX IF NOT EXISTS idx_opportunity_history_opportunity_changed
    ON marketing.opportunity_history (opportunity_id, changed_at DESC);

CREATE OR REPLACE FUNCTION marketing.capture_opportunity_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    actor_id bigint;
BEGIN
    actor_id := nullif(current_setting('app.user_id', true), '')::bigint;

    IF TG_OP = 'INSERT' THEN
        INSERT INTO marketing.opportunity_history
            (opportunity_id, row_version, operation, new_data, changed_by)
        VALUES (NEW.id, NEW.row_version, 'INSERT', to_jsonb(NEW), actor_id);
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO marketing.opportunity_history
            (opportunity_id, row_version, operation, old_data, new_data, changed_by)
        VALUES (NEW.id, NEW.row_version, 'UPDATE', to_jsonb(OLD), to_jsonb(NEW), actor_id);
        RETURN NEW;
    ELSE
        INSERT INTO marketing.opportunity_history
            (opportunity_id, row_version, operation, old_data, changed_by)
        VALUES (OLD.id, OLD.row_version, 'DELETE', to_jsonb(OLD), actor_id);
        RETURN OLD;
    END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_capture_opportunity_history
    ON marketing.opportunities;

CREATE TRIGGER trg_capture_opportunity_history
AFTER INSERT OR UPDATE OR DELETE
ON marketing.opportunities
FOR EACH ROW
EXECUTE FUNCTION marketing.capture_opportunity_history();

INSERT INTO marketing.opportunity_history
    (opportunity_id, row_version, operation, new_data)
SELECT opportunity.id, opportunity.row_version, 'BASELINE', to_jsonb(opportunity)
FROM marketing.opportunities AS opportunity
ON CONFLICT (opportunity_id, row_version, operation) DO NOTHING;

-- 3. Backfill the business date using the local calendar date, then enforce it.
UPDATE marketing.opportunities
SET opportunity_date = (created_at AT TIME ZONE 'Asia/Ho_Chi_Minh')::date
WHERE opportunity_date IS NULL;

ALTER TABLE marketing.opportunities
    ALTER COLUMN opportunity_date SET NOT NULL;

-- 4. Persist duplicate candidates for an explicit human review workflow.
CREATE TABLE IF NOT EXISTS marketing.opportunity_duplicate_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_signature text NOT NULL UNIQUE,
    opportunity_ids bigint[] NOT NULL,
    candidate_count integer NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'PENDING',
    resolution_note text,
    reviewed_by bigint,
    reviewed_at timestamp with time zone,
    first_detected_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_detected_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT opportunity_duplicate_reviews_count_check CHECK (candidate_count > 1),
    CONSTRAINT opportunity_duplicate_reviews_status_check
        CHECK (status IN ('PENDING', 'CONFIRMED_DUPLICATE', 'NOT_DUPLICATE', 'MERGED')),
    CONSTRAINT opportunity_duplicate_reviews_reviewer_fkey
        FOREIGN KEY (reviewed_by) REFERENCES core.members(id),
    CONSTRAINT opportunity_duplicate_reviews_resolution_check CHECK (
        (status = 'PENDING' AND reviewed_by IS NULL AND reviewed_at IS NULL)
        OR
        (status <> 'PENDING' AND reviewed_by IS NOT NULL
         AND reviewed_at IS NOT NULL AND resolution_note IS NOT NULL
         AND btrim(resolution_note) <> '')
    )
);

CREATE OR REPLACE FUNCTION marketing.refresh_opportunity_duplicate_reviews()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    affected_count integer;
BEGIN
    INSERT INTO marketing.opportunity_duplicate_reviews
        (candidate_signature, opportunity_ids, candidate_count)
    SELECT md5(concat_ws('|', project_id, owner_id, normalized_company_name,
                         pipeline_value, opportunity_date)),
           opportunity_ids,
           candidate_count::integer
    FROM marketing.opportunity_duplicate_candidates
    ON CONFLICT (candidate_signature) DO UPDATE
    SET opportunity_ids = EXCLUDED.opportunity_ids,
        candidate_count = EXCLUDED.candidate_count,
        last_detected_at = CURRENT_TIMESTAMP;

    GET DIAGNOSTICS affected_count = ROW_COUNT;
    RETURN affected_count;
END;
$$;

SELECT marketing.refresh_opportunity_duplicate_reviews();

COMMIT;
